id: P002961
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24013
  title: བྱིས་པའི་ལེགས་བཤད་དང་རྫོང་ཀའི་གཏམ།
  author: ''
  volumes:
    9c55a3d819304f129c375953ebf33982:
      image_group_id: I1KG24067
      title: ''
      volume_number: 1
      total_pages: 114
